runtime: python311
entrypoint: gunicorn -b :$PORT ideapools.wsgi

handlers:
- url: /static
  static_dir: static/
  secure: never  # Changed to never for local development

- url: /.* 
  script: auto
  secure: never  # Changed to never for local development

env_variables:
  DJANGO_SETTINGS_MODULE: 'ideapools.settings'
  DEBUG: 'False'
  SECRET_KEY: 'django-production-secret-key-123'
  DB_NAME: 'faas_db'
  DB_USER: 'postgres'
  DB_PASSWORD: 'faas-db-password-123'
  ALLOWED_HOSTS: 'faas-442515.ew.r.appspot.com'
  SERPER_API_KEY: '4fcf1f4b77fa58bb96a0071e2800dbb246e814d6'
  OPENAI_API_KEY: ${OPENAI_API_KEY}

vpc_access_connector:
  name: projects/faas-442515/locations/us-central1/connectors/vpc-connector
