services:
  web:
    build: .
    container_name: idea_pools_web
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
      container_name: idea_pools_postgres
      image: postgres:13.3-alpine
      restart: "unless-stopped"
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
          - postgres_data:/var/lib/postgresql/data
      ports:
          - 5433:5432

volumes:
  postgres_data:
    driver: local