# Generated by Django 5.1.3 on 2024-11-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder_assistance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_response_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
