# Generated by Django 3.2.25 on 2025-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder_assistance', '0003_project_personas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='market_analysis',
            field=models.TextField(blank=True, help_text='Markdown formatted market analysis', null=True),
        ),
    ]
