name: Trigger auto deployment for ideapools

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ideapools-AutoDeployTrigger-2678f4a3-63ab-4319-8315-a5fc7db4a476.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.IDEAPOOLS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: pugliairegistry.azurecr.io
          registryUsername: ${{ secrets.IDEAPOOLS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IDEAPOOLS_REGISTRY_PASSWORD }}
          containerAppName: ideapools
          resourceGroup: ideapulse
          imageToBuild: pugliairegistry.azurecr.io/faas:${{ github.sha }}
          
            

     

